### ISSUE TITLE
ogg Music Files Not Playing

### ISSUE THREAD

**Issue by Woolwit** [brain-workshop/brainworkshop#42]
I'm setting up a new Mac and was able to port brain-workshop to an M1 Mac Mini running Monterey. Everything is excellent, even importing my previous stats so I'm not having to start all over again. (Library > Application Support > Brain Workshop > data > stats.txt)
The letter name wav files play fine, but I can't get res/music/advance/Concert.ogg (etc) to play. I tried swapping them out with wav versions but still no luck playing the music between rounds.
Thanks!

**Comment by xantares** [comment]
first try to play the sound with ffmpeg to see if the problem is at some lower level:
```
ffplay Concert.ogg
```


if it works you can try to see if its a pyglet problem:
```
import pyglet
import time

musicplayer = pyglet.media.Player()
# wget https://github.com/brain-workshop/brainworkshop/raw/master/res/music/advance/Concert.ogg
music = pyglet.media.load('Concert.ogg', streaming=True)
musicplayer.queue(music)
print(musicplayer.volume)
musicplayer.play()
time.sleep(10)
```

**Comment by Woolwit** [comment]
Thank You!
ffplay Concert.ogg 
is working.
Pyglet Version: 1.5.23
Your Pyglet test is returning this error (same test did play a wav version)
```
% python3.10 testPyglet.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/wave.py", line 58, in __init__
    self._wave = wave.open(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 509, in open
    return Wave_read(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 163, in __init__
    self.initfp(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id
```

**Comment by xantares** [comment]
maybe ogg support is not available, try:

```
import pyglet.info
pyglet.info.dump_ffmpeg()
```

**Comment by Woolwit** [comment]
You're right about that. Something on my end to do with PATH maybe?

```
>>> import pyglet.info
>>> pyglet.info.dump_ffmpeg()
FFmpeg not available.
```
```
% which python3.10
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
```
```
% which ffmpeg
/usr/local/bin/ffmpeg
```

**Comment by xantares** [comment]
I dont think so, pyglet links to ffmpeg libs, check how it was installed

**Comment by Woolwit** [comment]
I think I'm just now seeing that support for ffmpeg 5.0 isn't part of pyglet 1.5.23, so that's probably my issue. I will keep an eye out for an update. Thanks for your help!

**Comment by xantares** [comment]
see https://github.com/pyglet/pyglet/issues/603

**Comment by Woolwit** [comment]
I saw that there was a pyglet update today.

> The latest 1.5.24 release has the ffmpeg changes backported.

I upgraded.
```% pip3.10 show pyglet
Name: pyglet
Version: 1.5.24
Summary: Cross-platform windowing and multimedia library
Home-page: http://pyglet.readthedocs.org/en/latest/
Author: Alex Holkner
Author-email: Alex.Holkner@gmail.com
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
```
But continue to have the same issue, of ogg files not playing.
```
% python3.10
>>> import pyglet.info
>>> pyglet.info.dump_ffmpeg()
FFmpeg not available.
```

**Comment by Woolwit** [comment]
I'm back! Still trying to figure this out. 
ffplay and the May 1 pyglet test (above) now playing ogg files.
But not between rounds of N-Back! Miss my dopamine hit!
Have v5.0.2 up and running.

**Comment by Woolwit** [comment]
For the life of me I could not get pyglet to find my ffmpeg.
Tried all sorts of things including everything ChatGpt could think of.

pyglet
/opt/homebrew/lib/python3.9/site-packages (2.0.4)

python3
/opt/homebrew/bin/python3

ffmpeg
/usr/local/bin/ffmpeg

Finally adding the OpenALDriver option, 
pyglet.options['audio'] = 'openal'  # set audio driver to OpenALDriver

and commenting out 
#cfg.USE_MUSIC = False

Got my dopamine hit of music back.
(I love those tracks!)
```
def test_music():
    try:
        import pyglet
        pyglet.options['audio'] = 'openal'  # set audio driver to OpenALDriver
        if pyglet.version >= '1.4':
            from pyglet.media import have_ffmpeg
            pyglet.media.have_avbin = have_ffmpeg()
            if not pyglet.media.have_avbin:
                #cfg.USE_MUSIC = False
```
