### ISSUE TITLE
No sound in Ubuntu 22.04

### ISSUE THREAD

**Issue by twoATOMS** [brain-workshop/brainworkshop#44]
The app works great except for one thing, it has no sound. The letters cannot be heard and I don't understand why. I get no errors no nothing.

**Comment by karlsmithcoalfire** [comment]
On Ubuntu, open brainworkshop.py in your favourite editor and change this line:

`pyglet.options['audio'] = ('directsound', 'openal', 'alsa', )`

to this:
`
pyglet.options['audio'] = ('pulse', 'directsound', 'openal', 'alsa', )`

worked for me!

**Comment by xantares** [comment]
could you try commenting the whole line and report if it still work ?
looks like by default it should already try to enable pulseaudio
