### ISSUE TITLE
Pyglet 2.x "Invalid value" exception

### ISSUE THREAD

**Issue by lgtout** [brain-workshop/brainworkshop#46]
I'm getting an error when I run 

`python3 /Users/bayo/dev/brainworkshop-5/brainworkshop.py`

```
Traceback (most recent call last):
  File "/Users/bayo/dev/brainworkshop-5/brainworkshop.py", line 1174, in <module>
    pyglet.gl.glLineWidth(calc_fontsize(2))
  File "/Users/bayo/dev/brainworkshop-5/pyglet/gl/lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x501): Invalid value. A numeric argument is out of range.
```

To resolve, I followed these instructions in the README, but no success:

> Copy the following folders into the brainworkshop folder: past, future and libfuturize. You can get those here: https://github.com/PythonCharmers/python-future
Copy the pyglet module into a pyglet folder. You can get pyglet here: http://www.pyglet.org/

```
> Python3 -V
> Python 3.10.8
```
I have pyglet 2.0.0 installed.

`pip3 install --upgrade pyglet==2.0.0`

Any assistance would be greatly appreciated.  Thank you!

**Comment by lgtout** [comment]
Fixed!  😅 
I had to do:
`pip3 uninstall pyglet`
`pip3 install --upgrade pyglet==1.5.27`

**Comment by xantares** [comment]
reopening; we should investigate pyglet 2.x compatibility

**Comment by xantares** [comment]
hello @lgtout could you double-check if this is fixed in master ?

**Comment by lgtout** [comment]
Thanks @xantares

I updated to the latest commit on master `9fdd7e`, and updated pyglet to `2.0` and `2.0.2.1`. Both fail.
The error is:
```
2022-12-21 11:58:48.662 Python[66848:6906930] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/34/vs3gz3zn02sbkz6z556qyszw0000gn/T/org.python.python.savedState
Traceback (most recent call last):
  File "/Users/bayo/dev/brainworkshop-5/brainworkshop.py", line 1173, in <module>
    pyglet.gl.glLineWidth(calc_fontsize(2))
  File "/opt/homebrew/lib/python3.10/site-packages/pyglet/gl/lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x501): Invalid value. A numeric argument is out of range.
```

**Comment by xantares** [comment]
this is something else then

**Comment by xantares** [comment]
, could you try to replace the line 1173 by:
```
print("fs=", calc_fontsize(2))
pyglet.gl.glLineWidth(1.0)
```

**Comment by lgtout** [comment]
@xantares That fixed it!  Thanks!
Output is `fs= 2.0`
```
> pip3 show pyglet
Name: pyglet
Version: 2.0.2.1
```

**Comment by xantares** [comment]
lets just drop that line, the max is 1.0 and the default anyways
