### ISSUE TITLE
Make Installing for Windows Users Easier

### ISSUE THREAD

**Issue by samcv** [brain-workshop/brainworkshop#7]
Here is a quick attempt that has supporting libraries. Hopefully this will work if the user just installs python and then launches brainworkshop.pyw

Windows Python installer link: https://www.python.org/downloads/windows/

Test file that (should) hopefully include everything but Python: [brainworkshop.zip](https://github.com/samcv/brainworkshop/files/2295386/brainworkshop.zip)

**Comment by xantares** [comment]
cx_freeze can also generate a single-file exe:

I had a go with:
```
cxfreeze brainworkshop.pyw --target-dir dist --zip-include=res --include-modules=pyglet.resource,pyglet.clock,pyglet.graphics,pyglet.sprite
```
unfortunately it doesn not load, I should figure out how to use the data dirs

**Comment by xantares** [comment]
It seems I succeeded, an archive is available on appveyor built from my fork:
https://ci.appveyor.com/api/buildjobs/js0stfx176ieeof4/artifacts/brainworkshop.zip

@samcv can you give me admin right to this repository so I could setup appveyor here too ?

**Comment by samcv** [comment]
@xantares it looks like I can't do that unless I create an organization and transfer the repo there. Does that sound good to you?

**Comment by xantares** [comment]
yes, that'd be even cooler

**Comment by xantares** [comment]
so brainworkwhop/brainworkshop ?
I think github will handle the redirection from samcv/brainworkshop automatically

**Comment by samcv** [comment]
@xantares  brainworkshop name was taken, so I made `brain-workshop` the name of the organization. You should have an invitation to join the organization in your email inbox.

**Comment by xantares** [comment]
da5fd25
